<?php

namespace Tests\Unit\Http\Requests;

use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\AddProgressionAdminRequest
 */
class AddProgressionAdminRequestTest extends TestCase
{
    /** @var \App\Http\Requests\AddProgressionAdminRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\AddProgressionAdminRequest();
    }

    #[Test]
    public function rules(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'taskNameNew' => [
                'required',
                'string',
                'max:255',
            ],
            'taskDetailsNew' => [
                'required',
                'string',
            ],
            'taskPriorityNew' => [
                'required',
            ],
        ], $actual);
    }

    // test cases...
}
