<?php

namespace Tests\Unit\Http\Requests;

use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\UpdateToolkitAdminRequest
 */
final class UpdateToolkitAdminRequestTest extends TestCase
{
    /** @var \App\Http\Requests\UpdateToolkitAdminRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\UpdateToolkitAdminRequest();
    }

    #[Test]
    public function rules(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'fileDescription' => [
                'required',
                'string',
                'max:255',
            ],
            'fileType' => [
                'required',
            ],
            'fileVersion' => [
                'nullable',
                'string',
                'max:25',
            ],
            'link' => [
                'nullable',
                'string',
                'max:255',
            ],
            'filePath' => [
                'nullable',
                'string',
                'max:255',
            ],
        ], $actual);
    }

    // test cases...
}
