<?php

namespace Tests\Unit\Http\Requests;

use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\UpdateProgressionAdminRequest
 */
class UpdateProgressionAdminRequestTest extends TestCase
{
    /** @var \App\Http\Requests\UpdateProgressionAdminRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\UpdateProgressionAdminRequest();
    }

    #[Test]
    public function rules(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'taskDetails' => [
                'required',
                'string',
            ],
            'taskNotes' => [
                'nullable',
                'string',
            ],
            'taskStatus' => [
                'required',
            ],
            'taskPriority' => [
                'required',
            ],
        ], $actual);
    }

    // test cases...
}
