<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\BoardListController
 */
class BoardListControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $boardLists = \App\Models\BoardList::factory()->times(3)->create();

        $response = $this->get(route('boardlist.index'));

        $response->assertOk();
        $response->assertViewIs('boardlist.index');
        $response->assertViewHas('posts');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $boardList = \App\Models\BoardList::factory()->create();

        $response = $this->get(route('boardlist.show', ['id' => $boardList->id]));

        $response->assertOk();
        $response->assertViewIs('boardlist.show');
        $response->assertViewHas('post');

        // TODO: perform additional assertions
    }

    // test cases...
}
