<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\PDFController
 */
class PDFControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function generate_pdf_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $financialReport = \App\Models\FinancialReport::factory()->create();
        $user = \App\Models\User::factory()->create();

        $response = $this->actingAs($user)->get(route('pdf.financialreport', ['id' => $id]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
