<?php

namespace Tests\Feature\Http\Controllers;

use PHPUnit\Framework\Attributes\Test;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\PDFController
 */
final class PDFControllerTest extends TestCase
{
    use RefreshDatabase;

    #[Test]
    public function financial_report_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();
        $financialReport = \App\Models\FinancialReport::factory()->create();
        $authUser = \App\Models\User::factory()->create();

        $response = $this->actingAs($authUser)->get(route('FinancialReport', ['id' => $id]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
