<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\PublicController
 */
class PublicControllerTest extends TestCase
{
    /**
     * @test
     */
    public function chapter_links_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('chapter.links'));

        $response->assertOk();
        $response->assertViewIs('public.chapterlinks');
        $response->assertViewHas('chapters');
        $response->assertViewHas('international');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function chapter_resources_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('board.resources'));

        $response->assertOk();
        $response->assertViewIs('public.resources');
        $response->assertViewHas('resources');

        // TODO: perform additional assertions
    }

    // test cases...
}
